version: "3"
env:
  VIDEO: "https://www.youtube.com/watch?v=d-KxsdWX9xE"
  PLAYLIST: "https://www.youtube.com/playlist?list=PLjNlQ2vXx1xbt30X8TcUfNzw_akVISXEu"
  TAG: "v1.0.0"
  IMAGE: "nestorpoliakov/tgstreamer"
tasks:
  run:
    desc: Run main.go
    cmds:
      - go run main.go --config=config/.local.yaml
  build:
    desc: Build and run docker image
    cmds:
      - docker buildx build --platform linux/amd64 -t $IMAGE:$TAG .
  push:
    desc: Push docker image to registry
    cmds:
      - docker push $IMAGE:$TAG
  vinfo:
    desc: Get video info
    cmds:
      - yt-dlp --dump-json "$VIDEO" > local/video_info.json

  pinfo:
    desc: Get playlist info
    cmds:
      - yt-dlp --dump-json "$PLAYLIST" > local/playlist_info.json
